WebAssignment/WebAssignment/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [

        url(r'^admin/', admin.site.urls),
        url(r'^teams/', include('teams.urls'))
]

WebAssignment/teams/urls.py
from django.conf.urls import include, url
from . import controllers

app_name = 'teams'
urlpatterns = [
    # /teams/
    url(r'^$', controllers.index, name='index'),


    # /teams/1/
    url(r'^(?P<id>[0-9]+)/$', controllers.detail, name='detail'),
    url(r'^(?P<id>[0-9]+)/player_create$', controllers.player_create, name='player_create'),
    url(r'^(?P<id>[0-9]+)/player_edit/(?P<playerid>[0-9]+)$', controllers.player_edit, name='player_edit'),
    url(r'^(?P<id>[0-9]+)/player_delete/(?P<playerid>[0-9]+)$', controllers.player_delete, name='player_delete'),
]

WebAssignment/teams/models.py
#DAL
from django.db import models

#Connection to Database,

#Team ID and Team Name
# Create your models here.

class FootballClubs(models.Model):
    clubname = models.CharField(max_length =250)
    teamID = models.CharField(max_length=10)


    def __str__(self):
        return self.clubname + ' - ' + str(self.id)
    # str casts .id function to string as it is inbuilt as an int

class Players(models.Model):
    footballClubs = models.ForeignKey(FootballClubs, on_delete=models.CASCADE)
    player_position = models.CharField(max_length=20)
    player_name = models.CharField(max_length=250)

    # def create(self):
    #     models.create(self)
    #     models.save()

    # def get(self, id):
    #     return self.get(id);
    #
    # def delete(self, id):
    #     self.delete(id)
    #     self.save()

    def __str__(self):
        return self.player_name

WebAssignment/teams/forms.py
from django import forms


#Just a django thing. Model goes into the HTMl
class PlayerForm(forms.Form):
    player_name = forms.CharField(label='Your name', max_length=250)
    player_position = forms.CharField(label='position', max_length=20)

WebAssignment/teams/controllers.py
from django.http import Http404
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from .models import FootballClubs, Players
from .forms import PlayerForm
#Controller

def index(request):
    all_clubname = FootballClubs.objects.all()

    return render(request, 'teams/index.html', {'all_clubname' : all_clubname}) #all_clubname is the model here
  # player = Players()
        # player.player_name = "blah"
        #
        # player.create()
def detail(request, id ):
    team = get_object_or_404(FootballClubs, pk=id)
    return render(request, 'teams/detail.html', {'team': team})

def player_create(request, id):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = PlayerForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            data = form.cleaned_data # The form gets the form results with the HTML; cleaned_data extracts the values
            team = FootballClubs.objects.get(pk=id) #retrieve the team based on our id

            # insert a new player into the team
            team.players_set.create(player_name=data['player_name'], player_position=data['player_position'])
            team.save()

            return HttpResponseRedirect('/teams/' + str(id))
    else:
        form = PlayerForm()

    return render(request, 'players/create.html', {'form': form}) #form is the model here

def player_edit(request, id, playerid):
    # if this is a POST request we need to process the form data
    team = FootballClubs.objects.get(pk=id) #retrieve the team based on our id
    player = team.players_set.get(pk=playerid)
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = PlayerForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            data = form.cleaned_data # The form gets the form results with the HTML; cleaned_data extracts the values

            # insert a new player into the team
            player.player_name=data['player_name']
            player.player_position=data['player_position']
            player.save()

            return HttpResponseRedirect('/teams/' + str(id))
    else:        
        form = PlayerForm(initial={'player_name':player.player_name, 'player_position': player.player_position})

    return render(request, 'players/edit.html', {'form': form, 'player': player})

def player_delete(request, id, playerid):
    # if this is a POST request we need to process the form data
    team = FootballClubs.objects.get(pk=id) #retrieve the team based on our id
    player = team.players_set.get(pk=playerid)
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        player.delete()
        return HttpResponseRedirect('/teams/' + str(id))
    else:
        form = PlayerForm(initial={'player_name':player.player_name, 'player_position': player.player_position})

    return render(request, 'players/delete.html', {'form': form, 'player': player})

WebAssignment/teams/views.py
from django.http import Http404
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from .models import FootballClubs, Players
from .forms import PlayerForm
import json

def index(request):
    all_clubname = FootballClubs.objects.all()

    return render(request, 'teams/index.html', {'all_clubname' : all_clubname})
  # player = Players()
        # player.player_name = "blah"
        #
        # player.create()
def detail(request, id ):
    team = get_object_or_404(FootballClubs, pk=id)
    return render(request, 'teams/detail.html', {'team': team})

def player_create(request, id):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = PlayerForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            data = form.cleaned_data # The form gets the form results with the HTML; cleaned_data extracts the values
            team = FootballClubs.objects.get(pk=id) #retrieve the team based on our id

            # insert a new player into the team
            team.players_set.create(player_name=data['player_name'], player_position=data['player_position'])
            team.save()

            return HttpResponseRedirect('/teams/' + str(id))
    else:
        form = PlayerForm()

    return render(request, 'players/create.html', {'form': form})

WebAssignment/teams/templates/players/create.html
<body style="background-color:white;">
<body align="center">
<img src="http://i61.photobucket.com/albums/h41/tommieds/header_zpsw29j1xsz.png" alt="some_text" style="width:800px;height:125px;">
<img src="http://i61.photobucket.com/albums/h41/tommieds/fillspace_zpsd2ovqr1y.png" alt="some_text" style="float:right;width:500px;height:1200px;">
<img src="http://i61.photobucket.com/albums/h41/tommieds/fillspace_zpsd2ovqr1y.png" alt="some_text" style="float:left;width:500px;height:1200px;">

<h3 style="font-family:Calibri;font-size:200%;" >Add a new player</h3>




<form action="player_create" method="post">
    {% csrf_token %}
    <h2 style="font-family:Calibri;font-size:150%;" >{{ form }}</h2>
    <input type="submit" value="Submit" />
</form>

<p><button onclick="javascript:history.go(-1)">Back</button> </p>

WebAssignment/teams/templates/players/delete.html
<body style="background-color:white;">
<body align="center">
<img src="http://i61.photobucket.com/albums/h41/tommieds/header_zpsw29j1xsz.png" alt="some_text" style="width:800px;height:125px;">
<img src="http://i61.photobucket.com/albums/h41/tommieds/fillspace_zpsd2ovqr1y.png" alt="some_text" style="float:right;width:500px;height:1200px;">
<img src="http://i61.photobucket.com/albums/h41/tommieds/fillspace_zpsd2ovqr1y.png" alt="some_text" style="float:left;width:500px;height:1200px;">


<h2 style="font-family:Calibri;font-size:150%;" ><p> You are about to delete: </p> </h2>
<h2 style="font-family:Calibri;font-size:150%;" ><p>{{ player }} </p> </h2>
<h2 style="font-family:Calibri;font-size:150%;" > <p>   Are you sure you wish to do this? </p> </h2>
<form action="{{player.id}}" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" />

</form>
<p><button onclick="javascript:history.go(-1)">Back</button> </p>

WebAssignment/teams/templates/players/edit.html
<body style="background-color:white;">
<body align="center">
<img src="http://i61.photobucket.com/albums/h41/tommieds/header_zpsw29j1xsz.png" alt="some_text" style="width:800px;height:125px;">
<img src="http://i61.photobucket.com/albums/h41/tommieds/fillspace_zpsd2ovqr1y.png" alt="some_text" style="float:right;width:500px;height:1200px;">
<img src="http://i61.photobucket.com/albums/h41/tommieds/fillspace_zpsd2ovqr1y.png" alt="some_text" style="float:left;width:500px;height:1200px;">


<h3>Edit a player</h3>

<form action="{{player.id}}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>


<p><button onclick="javascript:history.go(-1)">Back</button> </p>

WebAssignment/teams/templates/teams/detail.html
<body style="background-color:white;">
<body align="center">
<img src="http://i61.photobucket.com/albums/h41/tommieds/header_zpsw29j1xsz.png" alt="some_text" style="width:800px;height:125px;">
<img src="http://i61.photobucket.com/albums/h41/tommieds/fillspace_zpsd2ovqr1y.png" alt="some_text" style="float:right;width:500px;height:1200px;">
<img src="http://i61.photobucket.com/albums/h41/tommieds/fillspace_zpsd2ovqr1y.png" alt="some_text" style="float:left;width:500px;height:1200px;">

<h3 style="font-family:Calibri;color:black; font-size:350%;" > {{team.clubname}}</h3>

    {% for player in team.players_set.all %}
    <h3 style="font-family:Calibri;color:black; font-size:150%;" >	<li>{{ player.player_name }} - {{player.player_position }} </li> </h3>
    <h3 style="font-family:Calibri;color:black; font-size:150%;" ><a href="/teams/{{team.id}}/player_edit/{{player.id}}">Edit</a> </h3>
    <h3 style="font-family:Calibri;color:black; font-size:150%;" ><a href="/teams/{{team.id}}/player_delete/{{player.id}}">Delete </a> </h3>
    {% endfor %}
</ul>
{% if error_message %}
    <p><strong>{{error_message}}</strong></p>
{% endif %}

<h3 style="font-family:Calibri;color:black; font-size:150%;" ><a href="/teams/{{team.id}}/player_create">Add new player</a> </h3>

<FORM>

<INPUT Type="BUTTON" Value="Back" Onclick="window.location.href='http://127.0.0.1:8000/teams/'">
</FORM>
</body>

WebAssignment/teams/templates/teams/index.html
<body style="background-color:white;">
<body align="center">
<img src="http://i61.photobucket.com/albums/h41/tommieds/header_zpsw29j1xsz.png" alt="some_text" style="width:800px;height:125px;">
<img src="http://i61.photobucket.com/albums/h41/tommieds/fillspace_zpsd2ovqr1y.png" alt="some_text" style="float:right;width:500px;height:1200px;">
<img src="http://i61.photobucket.com/albums/h41/tommieds/fillspace_zpsd2ovqr1y.png" alt="some_text" style="float:left;width:500px;height:1200px;">


{% if all_clubname %}
    <h3 style="font-family:Calibri;color:black; font-size:350%;" > Here are all the teams in the league: </h3>
        {% for club in all_clubname %}
<h2 style="font-family:Calibri;font-size:200%;" >  <li><a href="{% url 'teams:detail' club.id %}">{{club.clubname}}</a></li> </h2>
        {% endfor %}
    </ul>
 {% else%}
    <h3>You dont have any players listed</h3>
 {% endif %}

<img src="http://vignette4.wikia.nocookie.net/peel/images/0/01/Football.jpg/revision/latest?cb=20150130151652" alt="some_text" style="width:600px;height:300px;">
</body>